name: Deploy via FTP
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: cp146.netafraz.com
          user: amirdash
          password: amir1400
          localDir: "/"
          remoteDir: "/project"
          options: "--delete --ascii"

            
