name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: genietim/ftp-action@v4.0.1
      with:
        host: cp146.netafraz.com
        user: amirdash
        password: amir1400
        localDir: "dist"
        remoteDir: "public_html"
            
